[General]
firstTime=false
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\x5\0\0\0-\0\0\au\0\0\x4-\0\0\x5\a\0\0\0/\0\0\as\0\0\x4+\0\0\0\0\0\0\0\0\a\x80\0\0\x5\a\0\0\0/\0\0\as\0\0\x4+)
geometryNomacs=@Rect(1287 47 621 1021)
windowGeometry=@Rect(1447 47 461 1021)
windowMaximized=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x1\xcd\0\0\x3\xcb\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
currentAppMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false

[DisplaySettings]
bgColorNoMacsRGBA=4293914607
bgColorWidgetRGBA=1711276032
iconColorRGBA=4281545523

[DkAppManager]
Apps\size=0

[DkFilePreview]
windowPosition=1

[DkMetaDataHUD]
keyValues=File.Filename, File.Path, File.Size, Exif.Image.Make, Exif.Image.Model, Exif.Image.DateTime, Exif.Image.ImageDescription, Exif.Photo.ISO, Exif.Photo.FocalLength, Exif.Photo.ExposureTime, Exif.Photo.Flash, Exif.Photo.FNumber
numColumns=-1
windowPosition=3

[GlobalSettings]
lastDir=/home/blackbloodredkiss/CU/python/hw3/thumbnails
recentFiles=/home/blackbloodredkiss/CU/python/hw3/thumbnails/thumb_1.jpg, /home/blackbloodredkiss/Pictures/Screenshots/2024-08-19_02-34-28.png, /home/blackbloodredkiss/Pictures/Screenshots/2024-08-19_02-30-12.png, /home/blackbloodredkiss/Downloads/Telegram Desktop/image_2024-07-26_21-37-17.png
recentFolders=/home/blackbloodredkiss/CU/python/hw3/thumbnails, /home/blackbloodredkiss/Pictures/Screenshots, /home/blackbloodredkiss/Downloads/Telegram Desktop

[SynchronizeSettings]
checkForUpdates=true
disableUpdateInteraction=false
