theme = "nord"

[editor]
bufferline = "multiple"

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
C-h = ":buffer-previous"
C-l = ":buffer-next"

[keys.select]
l ={l= ":pipe ~/.config/scripts/ll_helix.sh"}
